import { Router } from 'express';
import auth from './auth.js';
import verifications from './verifications.js';
import doctors from './doctors.js';
import patients from './patients.js';
import facilities from './facilities.js';
import healthcare from './healthcare.js';
import appointments from './appointments.js';
import messages from './messages.js';
import medicalRecords from './medicalRecords.js';
import reports from './reports.js';
import ambulances from './ambulances.js';
import emergency from './emergency.js';
import donors from './donors.js';
import blood from './blood.js';
import notifications from './notifications.js';
import feedback from './feedback.js';
import admin from './admin.js';
import analytics from './analytics.js';
import demo from './demo.js';

const router = Router();
router.use('/auth', auth);
router.use('/verifications', verifications);
router.use('/doctors', doctors);
router.use('/patients', patients);
router.use('/facilities', facilities);
router.use('/healthcare', healthcare);
router.use('/appointments', appointments);
router.use('/messages', messages);
router.use('/medical-records', medicalRecords);
router.use('/reports', reports);
router.use('/ambulances', ambulances);
router.use('/emergency', emergency);
router.use('/donors', donors);
router.use('/blood', blood);
router.use('/notifications', notifications);
router.use('/feedback', feedback);
router.use('/admin/demo', demo);
router.use('/admin', admin);
router.use('/analytics', analytics);

export default router;
